name: Build A20s Android 12 ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ROM manifest
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick \
            lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev \
            libssl-dev libxml2 libxml2-utils lzop openjdk-11-jdk pngcrush rsync schedtool squashfs-tools \
            xsltproc zip zlib1g-dev repo ccache python3 python3-pip

      - name: Initialize ROM source
        run: |
          mkdir rom && cd rom
          repo init -u https://github.com/PixelExperience/manifest -b twelve-plus
          repo sync -j2 --force-sync --no-tags --no-clone-bundle

      - name: Clone device trees
        run: |
          cd rom
          git clone https://github.com/Saleem-programmer91754/device_samsung_a20s.git -b android-12 device/samsung/a20s
          git clone https://github.com/Saleem-programmer91754/vendor_samsung_a20s.git -b android-12 vendor/samsung/a20s
          git clone https://github.com/Saleem-programmer91754/kernel_samsung_a20s.git -b android-12 kernel/samsung/a20s

      - name: Clean previous builds to save space
        run: |
          cd rom
          rm -rf out

      - name: Prepare environment and lunch
        run: |
          cd rom
          source build/envsetup.sh
          lunch aosp_a20s-userdebug

      - name: Build ROM with limited parallel jobs
        run: |
          cd rom
          make -j4 systemimage

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: system-img
          path: rom/out/target/product/a20s/system.img
